# Generated by Django 3.0.5 on 2020-04-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesspic', models.ImageField(blank=True, upload_to='images/')),
                ('businessname', models.CharField(max_length=30)),
                ('businessemail', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
